name: Build and Deploy
on:
   push:
      branches:
         - main # or master before October 2020
jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v3

         - name: Cache
           uses: actions/cache@v3
           with:
              path: vendor/bundle
              key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
              restore-keys: |
                 ${{ runner.os }}-gems-
         - name: Deploy
           with:
              branch: 'gh-pages'
